"""Initial migration

Revision ID: c38b83794246
Revises: 
Create Date: 2026-05-27 23:28:02.607060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38b83794246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversion_type', sa.String(length=50), nullable=False),
    sa.Column('input_value', sa.String(length=100), nullable=False),
    sa.Column('result_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
