scores = [178, 165, 145, 250, 138, 230]
teams = ["RCB", "CSK", "LSG"]
print("Scores of ipl teams:", scores)
# 1- append()
scores.append(200)
print("Added 200 to the scores:", scores)
# 2- insert()
scores.insert(2, 157)
print("inserted at the 2nd index:", scores)
# 3- remove()
scores.remove(145)
print("removed from the list :", scores)
# 4- pop(index)
print("poped out the value in the index:", scores.pop(0))
# 5- index()
print("The index value of 250 :", scores.index(250))
print("The elements are:", scores[::-1])
print("The elements are:", teams[2::-1])
print("the element of index :", scores[:2])
print("the element of index :", teams[:4])
# 6- reverse()
reverse_list = scores[::-1]
print("The scores list is reversed:", reverse_list)
# 7- sort()
scores.sort()
print("The scores are sorted:", scores)
# 8- count()
Total = scores.count(250)
print("Total count:", Total)
# 9- extend()
teams.extend(scores)
print("The teams merged with scores :", teams)
# 10- clear()
print("clear all the scores:", scores.clear())
# 11- del
del teams[0:5]
print("After deletion:", teams)
# 12- len
print(len(teams))
print(len(scores))
