num_tup = (1, 2, 33, 56, 78, 2, 1, 2, 2, 78)
alph_tup = ("a", "b", "g", "h", "g", "a", "g", "h", "p")
print(num_tup)
print(alph_tup)
# count()
print("The count of 2:", num_tup.count(2))
print("The count of alphabet g:", alph_tup.count("g"))
# index()
print("Element is : ", num_tup[-5])
print("element is:", num_tup[4])
print("element:", alph_tup[0:-1])
