"""upgrading to db

Revision ID: 671b9c473c50
Revises:
Create Date: 2026-05-28 11:33:30.162310

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "671b9c473c50"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("song", schema=None) as batch_op:
        batch_op.alter_column("poster", existing_type=sa.VARCHAR(length=500), nullable=False)
        batch_op.drop_column("emoji")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("song", schema=None) as batch_op:
        batch_op.add_column(sa.Column("emoji", sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column("poster", existing_type=sa.VARCHAR(length=500), nullable=True)

    # ### end Alembic commands ###
