"""Initial migration

Revision ID: 2c4b0825aa06
Revises:
Create Date: 2026-05-29 11:04:00.861436

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c4b0825aa06"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "song",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("artist", sa.String(length=100), nullable=False),
        sa.Column("mood", sa.String(length=50), nullable=False),
        sa.Column("poster", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("song")
    # ### end Alembic commands ###
