"""Setup database inside instance folder

Revision ID: 02acd519097a
Revises:
Create Date: 2026-05-27 21:18:58.502390

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02acd519097a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("genre", sa.String(length=100), nullable=False),
        sa.Column("mood", sa.String(length=50), nullable=False),
        sa.Column("emoji", sa.String(length=10), nullable=False),
        sa.Column("poster", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movies")
    # ### end Alembic commands ###
